name: GNU Coding Style Check (Syscall branch only)

on:
  push:
    branches: [ "feature/syscall" ]
  pull_request:
    branches: [ "development" ]

jobs:
  gnu-style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Thiết lập môi trường thực thi
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential gcc \
          make

    - name: Cài đặt các công cụ kiểm tra
      run: |
        sudo apt-get install -y \
          clang-format \
          cppcheck \
          valgrind

    - name: Kiểm tra tuân thủ Coding style GNU trong các tệp liên quan đến System Call
      run: |
        clang-format --style=GNU --dry-run -Werror \
          src/syscall*.c \
          src/sys_*.c
